gladiaio/gladia

src/requirements.txt
redondant with 
https://github.com/gladiaio/gladia/blob/main/src/gpu.Dockerfile#L14
=> remove redondant api-utils install

src/apis/image/image/super-resolution.py
Fix #136 by changing super-resolution default model from `esrgan` to `idealo-psnr-small`.
=> Changed super-resolution default model to idealo-psnr-small

src/gpu.Dockerfile
`gpu.Dockerfile` first remove the default `gladia-api-utils` package before installing the target one.
Closes #134, #125, #124, #123, #121, #118, #114, #113, #103
=> Dockerfile remove gladia-api-utils package before reinstalling it

src/api_utils/gladia_api_utils/responses.py, src/api_utils/gladia_api_utils/submodules.py
Three classes have been created to specify the media_type and schema of the response:
* `ImageResponse` for the */image tasks
* `AudioResponse ` for the */audio tasks
* `VideoResponse ` for the */video tasks
Those classes are used to specify the `response_class` and `responses` params of the router (POST routes only).
Fixes #223
=> Set response media_type accordingly to output modality

README.md
In the global `README.md`, we add the `-c` option when starting the tests. 
It allows tests to continue running even if some of them fail early. The user still has a final report on how many tests passed/failed/skipped. 
As of now, the fist time a user run the tests, it might fail for "bad" reasons (ie. the model is not already loaded for instance). Add the `-c` option allows the user to perform a full run of the tests even if some fail, allowing him to witness that the solution is not completely failing : just few tests among all of them.
=> docs: add continue option to tests in case some fail

src/apis/text/text/similarity.py
This PR replaces both sentences default values by empty strings. 
* When the API is called with an empty sentence, then it takes the default value
* The similarity is **equal** in both following cases : 
1. `sentence_1 = "I like Python because I can build AI applications"` and `sentence_2="Second sentence to compare to"` (We explicitly set the default values)
2. and `sentence_1 = ""` and `sentence_2  = ""` (We fallback to the defaults values)
* If `sentence_1 = ""`, then the resulting similarity will be the similarity between `sentence_1 = "I like Python because I can build AI applications"` and any `sentence_2` value
* If `sentence_2 = ""`, then the resulting similarity will be the similarity between `sentence_2 = "Second sentence to compare to"` and any `sentence_1` value
* Whenever the …
=> fix(text/text/similarity): replace sentences default values by empty strings

.pre-commit-config.yaml, CONTRIBUTING.md, README.md
This PR adds pre commit hooks to the project. 
For now, it only list `black` in the list of hooks. 
In order to run the hooks in the CI, we will have to use https://pre-commit.ci/ . The request has been sent and is under review on their side.
=> chore: add pre commit hooks to the project

src/api_utils/gladia_api_utils/submodules.py
When doing a GET request on a route leading to a task, the user will no longer receive a list listing each available model name but rather a list describing each model with its metadata (i.e `latency_grade`).
Closes #337
=> GET requests now return a dict instead of a list

.pre-commit-config.yaml, CONTRIBUTING.md
This PR adds [commitizen check](https://commitizen-tools.github.io/commitizen/check/) to pre-commit hooks. 
Once the user has performed the `pre-commit install` command, this pre-commit should run both locally and in the CI. 
closes https://github.com/gladiaio/gladia/issues/291
=> chore(pre-commit): add commitizen check to pre-commit hooks

src/api_utils/gladia_api_utils/casting.py
adding the capability to add metadata to an image raw response
and How it looks like on the backend side
=> feat(casting.py): add the ability to add metadata tresponse headers

src/api_utils/gladia_api_utils/triton_helper/TritonClient.py, src/apis/text/text/hate-speech-detections/Hate-speech-CNERG-dehatebert-mono-english/Hate-speech-CNERG-dehatebert-mono-english.py, src/apis/text/text/language-detections/xlm-roberta-base-language-detection/xlm-roberta-base-language-detection.py, src/apis/text/text/named-entity-recognitions/dbmdz-bert-large-cased-finetuned-conll03-english/dbmdz-bert-large-cased-finetuned-conll03-english.py, src/apis/text/text/sentiment-analyses/nlptown-bert-base-multilingual-uncased-sentiment/nlptown-bert-base-multilingual-uncased-sentiment.py, src/apis/text/text/similarities/all-MiniLM-L6-v2/.git_path, src/apis/text/text/similarities/all-MiniLM-L6-v2/all-MiniLM-L6-v2.py, src/config.json
In this PR : 
* `text/text/similarity/&model=all-MiniLM-L6-v2` is migrated to triton
* in `all-MiniLM-L6-v2.py`, `cos_sim()` is implemented on its own so that we do not have to import `sentence-transformers.util`, which under the hood imports import  several other packages (see [here](https://github.com/UKPLab/sentence-transformers/blob/master/sentence_transformers/util.py))
* the new triton model is added to the pre-loaded models via `config.json`
* `TritonClient` is modified so that several inputs can be registered
* As a result, existing triton models that used the former way of registering inputs are adapted to the new way
=> feat: add all-MiniLM-L6-v2 to triton

src/api_utils/gladia_api_utils/casting.py
BREAKING CHANGE: int and bool are now output as json {"prediction": int/bool}
closes: https://github.com/gladiaio/gladia/issues/490
=> fix(casting): move all output to json

.github/workflows/gladia-builder.yml
Pytorch need to read all GPU, even if we want it to use only one of them.
=> ci(builder): let pytorch see all GPU

src/apis/text/text/sentiment-analyses/nlptown-bert-base-multilingual-uncased-sentiment/nlptown-bert-base-multilingual-uncased-sentiment.py
All the output of the other models was : 
{ "label": str, "score": float} exept nlptown-bert-base-multilingual-uncased-sentiment who was {"prediciton": str}
Now it is all the same.
=> fix(nlptown-bert-base-multilingual-uncased-sentiment): unify output format to {'label':str, 'score':float}

src/api_utils/gladia_api_utils/submodules.py
* previously files were requested using `Form` instead of `File`.
* `endpoint_parameters_description["some_value"]` now contains a `constructor` key telling which constructor to use.
* `description` is swagger is now empty instead of containing `"TODO"`
=> fix: files are now requested using the File constructor instead of Form

src/api_utils/gladia_api_utils/io.py
Investigating around the _open() function in src/api_utils/gladia_apis_utils/io.py, I saw some parts of the code are never used as the optional argument 'btype'.
This function could be simplified to clear it.
=> refactor(api_utils): removed unused code in _open() function

src/api_utils/gladia_api_utils/model_management.py, src/apis/image/image/background-removal-models/mobilenet/env.yaml, src/apis/image/image/background-removal-models/mobilenet/mobilenet.py, src/apis/image/image/background-removal.py, src/env.yaml
Exporting the model as ONNX format allows us to:
1. Remove the TF import which was time consuming (~1s)
2. Remove the env.yaml as there is no memory leak du to the tf removal
Note : Speed up the end2end call by 6x
=> perf(background-removal): switch background removal mobilenet model to onnx format

.github/workflows/gladia-builder.yml
The idea is to remove all secret from the workflow and move them elsewhere 🥷 
Thus, PR from non-collaborators fork should not be blocked.
=> ci(build): remove secret dependencies

.github/workflows/deploy-completion.yml, .github/workflows/gladia-latest-deploy.yml
Using the previous method, the slack webhook was readable in action logs, and I still had issue with formatting. To unblock the process, I moved it from the deploy workflow to a dedicated workflow that will be triggered on deploy workflow's completion. 
Workflow_run runs on the default branch and has access to secrets since it's "disconnected" from the source PR. I still need to work on it but you get the idea.
Another cool option is that it's easier to catch success and failure.
=> ci(slack): use a run trigger for slack notifier

src/api_utils/gladia_api_utils/submodules.py
Fixes #838 
If `urlopen` failed, `clean_kwargs_based_on_router_inputs` return a `success=False` value
=> fix(TaskRouter): handle invalid url (#838)

src/main.py
In the `config.json` you can now do: `"image":["background-removal?model=mobilenet"]`.
Note : This would change nothing in the behaviour (you could still target `xception` in this example).
@jqueguiner  if you have any suggestion, feel free to let me know.
We may want to have an instance `I_A` handling only model `M_A` and an instance `I_B` handling only model `M_B`.
This redirection between `I_A` and `I_B` is based on the `config.json` file. Thus we need to be able to specify the model.
Again, `gladia/gladia` is agnostic of this behaviour, it change nothing here, only on the routing.
=> feat: config can specify model

.github/workflows/gladia-latest-deploy.yml
Avoid restart all at once. 
Will work better once healthcheck available.
=> ci(rollout): sequentially wait for rollout success

.github/workflows/upload-api-utils-to-pypi.yaml
the changed files action is probably failing because our runners have some path in read-only or something related (to be investigated).
This is a simple action, we can delegate to the GH runner until we fix this.
=> ci(pypi): delegate to GH as workaround

.github/workflows/gladia-builder.yml
Also testing the persistent model directory for tests.
=> ci(docker): always prune old data a after successful build

src/apis/audio/text/speaker-diarization/pyannote-speaker_diarization/pyannote-speaker_diarization.py
The model crashs when the first try/catch fails as pipeline is not defined.
=> fix(speaker-diarization): return if pipeline loading fails
