gladiaio/gladia

README.md
Under the shields.io badge, the Twitter text link was incorrect ;)
Is the text link for accessibility purpose ?
Good luck in your new gig !!!
I wish you the best ;)
David
=> Fix twitter link

src/apis/image/image/background-removals/mobilenet/mobilenet.py, src/apis/image/image/background-removals/xception/xception.py, src/apis/image/image/colorization.py, src/apis/image/image/colorizations/deoldify-artistic/deoldify-artistic.py, src/apis/image/image/colorizations/deoldify-stable/deoldify-stable.py, src/apis/image/image/face-blurings/ageitgey/ageitgey.py, src/apis/image/image/restoration.py, src/apis/image/image/super-resolutions/idealo-psnr-small/idealo-psnr-small.py, src/apis/image/image/uncolorizations/v1/v1.py
Documentation, type hinting and minor reworks Image to Image tasks.
Tasks concerned:
* `background-removal`
* `colorization`
* `face-bluring`
* `super-resolution`
* `uncolorization`
Note : Waiting this PR to be approved before reworking other tasks.
=> Image to Image tasks documented, type hinted and slightly reworked 

.gitignore, src/apis/image/text/asciifies/ramesh-aditya/asciifyrunner.py, src/apis/text/text/sentiment-analyses/distilbert-base-uncased-finetuned-sst-2-english/distilbert-base-uncased-finetuned-sst-2-english.py, src/apis/text/text/sentiment-analyses/distilbert-base-uncased/distilbert-base-uncased.py
Removed multiple unused prints in APIs (only).
Delete multiple unused prints in:
* `asciifyrunner`
* `distilbert-base-uncased-finetuned-sst-2-english`
* `distilbert-base-uncased`
(git) Ignore files:
* `.idea/`
Note : There are still multiple debug prints that should be removed but they will be threaded in an other PR
=> Delete multiple unused prints in APIs

src/main.py
General behavior has not been changed. Wrapping functions has been created and `import_submodules` has been split into multiple functions.
=> Script for the api launch reworked

src/setup_custom_envs.py
fixes https://github.com/gladiaio/gladia/issues/141
=> [FEAT][ENV] build custom env recursively from a specific folder

src/apis/text/text/hate-speech-detections/Hate-speech-CNERG-dehatebert-mono-english/Hate-speech-CNERG-dehatebert-mono-english.py
https://github.com/gladiaio/gladia/issues/145
=> [FIX] fix device placement on hate speech recognition

src/setup_custom_envs.py
Closes  https://github.com/gladiaio/gladia/issues/143
=> [FEAT][CUSTOM_ENV] add multithreading for build

src/setup_custom_envs.py
closes : https://github.com/gladiaio/gladia/issues/151
closes : https://github.com/gladiaio/gladia/issues/153
=> [FIX][FEAT] move setup custom env to flags + fix des issues

src/gpu.Dockerfile
closes : https://github.com/gladiaio/gladia/issues/170
=> add cache location for transformers to use mutualized cache

src/gpu.Dockerfile
closes : https://github.com/gladiaio/gladia/issues/165
=> add TOKENIZERS_PARALLELISM=True

src/unit-test/test.py
closes : https://github.com/gladiaio/gladia/issues/172
=> add unit test --after-endpoint skipping option

src/gpu.Dockerfile
closes : https://github.com/gladiaio/gladia/issues/174
=> add docker arg to force custom_env builds

src/api_utils/gladia_api_utils/casting.py, src/api_utils/gladia_api_utils/citation.py, src/api_utils/gladia_api_utils/download_active_models.py, src/api_utils/gladia_api_utils/file_management.py, src/api_utils/gladia_api_utils/image_management.py, src/api_utils/gladia_api_utils/io.py, src/api_utils/gladia_api_utils/model_management.py, src/api_utils/gladia_api_utils/options.py, src/api_utils/gladia_api_utils/submodules.py, src/api_utils/gladia_api_utils/system.py, src/api_utils/setup.py, src/gpu.Dockerfile, src/venv-builder/default_common_packages.txt
Merge the `gladia-api-utils` package within this repository.
`src/venv-builder/default_common_packages.txt` need to have `-e /app/api_utils/` replaced by `-e $ABSOLUTE_PATH_TO_SRC/api_utils/` but it will done in an other PR.
=> Refactor: Merge with gladia-api-utils

README.md
closes : https://github.com/gladiaio/gladia/issues/199
=> Fix / README.md site link

src/api_utils/gladia_api_utils/casting.py
* `cast_response` now call functions reducing code complexity.
* unused class `NumpyEncoder` has been deleted
* logs has been removed (and replaced by warnings when needed)
* imports has been sorted
=> Fix code smells in castings

README.md, src/gpu.Dockerfile, src/run_server_prod.sh
you can now set port using API_SERVER_PORT_HTTP
=> adjustable server port

.github/ISSUE_TEMPLATE/bug_report.md
=> Create an issue template for bug report

.gitignore, README.md, src/docker-compose.dev.yaml, src/docker-compose.prod.yaml, src/docker-compose.yaml
Final status: Success
Test Passed: 38/38 (100.0%)
Test Failed: 0/38  (0.0%)
Test Skipped: 0
=> deploy in production with docker compose

src/gpu.Dockerfile
=> fix curl ref in docker

.github/ISSUE_TEMPLATE/feature_request.md
=> Create issue template for feature request

src/tools/run_ci_pr.py
closes : https://github.com/gladiaio/gladia/issues/321
=> fix(run_ci_pr): fix return of the smallest PR associated to a commit

src/apis/image/text/classification.py
closes : https://github.com/gladiaio/gladia/issues/320
=> fix(image-classification): fix missing top_k param in classification abstract class

src/tools/run_ci_pr.py
closes : https://github.com/gladiaio/gladia/issues/330
=> fix(run_ci_pr): add the support for parenthesis commit formatting in deploy message

src/api_utils/gladia_api_utils/TorchvisionModel.py, src/api_utils/gladia_api_utils/__init__.py, src/apis/image/text/classifications/mnasnet0_5/mnasnet0_5.py
Add a wrapping class for torchvision models : `TorchvisionModel`
=> feat: TorchvisionModel wrapper

src/apis/image/text/classifications/vgg16_bn/vgg16_bn.py
=> feat(vgg16_bn): add VGG16_BN to image/text/classification

src/apis/image/text/classifications/swin_b/swin_b.py
=> feat(swin_b): add Swin_B to image/text/classification

src/apis/image/text/classifications/swin_s/swin_s.py
=> feat(swin_s): add Swin_S to image/text/classification

src/apis/image/text/classifications/vgg13/vgg13.py
=> feat(vgg13): add VGG13 to image/text/classification

src/apis/image/text/classifications/vgg13_bn/vgg13_bn.py
=> feat(vgg13_bn): add VGG13_BN to image/text/classification

src/apis/image/text/classifications/vgg19_bn/vgg19_bn.py
=> feat(vgg19_bn): add VGG19_BN to image/text/classification

src/apis/image/text/classifications/vgg11_bn/vgg11_bn.py
=> feat(vgg11_bn): add VGG11_BN to image/text/classification

src/apis/image/text/classifications/swin_t/swin_t.py
=> feat(swin_t): add Swin_T to image/text/classification

src/apis/image/text/classifications/vit_b_32/vit_b_32.py
=> feat(vit_b_32): add ViT_B_32 to image/text/classification

src/apis/image/text/classifications/vit_l_32/vit_l_32.py
=> feat(vit_l_32): add ViT_L_32 to image/text/classification

src/apis/image/text/classifications/vit_h_14_swag_e2e_v1/vit_h_14_swag_e2e_v1.py, src/apis/image/text/classifications/vit_h_14_swag_linear_v1/vit_h_14_swag_linear_v1.py
=> feat(vit_h_14): add vit_h_14 to image/text/classification

src/apis/image/text/classifications/vit_b_16_swag_e2e_v1/vit_b_16_swag_e2e_v1.py, src/apis/image/text/classifications/vit_b_16_swag_linear_v1/vit_b_16_swag_linear_v1.py, src/apis/image/text/classifications/vit_b_16_v1/vit_b_16_v1.py
=> feat(vit_b_16): add vit_b_16 to image/text/classification

src/apis/image/text/classifications/resnext50_32x4d_v1/resnext50_32x4d_v1.py, src/apis/image/text/classifications/resnext50_32x4d_v2/resnext50_32x4d_v2.py
=> feat(resnext50_32x4d): add resnext50_32x4d to image/text/classification

src/apis/image/text/classifications/resnext101_64x4d_v1/resnext101_64x4d_v1.py
=> feat(resnext101_64x4d): add resnext101_64x4d to image/text/classification

src/apis/image/text/classifications/regnet_y_16gf_swag_e2e_v1/regnet_y_16gf_swag_e2e_v1.py, src/apis/image/text/classifications/regnet_y_16gf_swag_linear_v1/regnet_y_16gf_swag_linear_v1.py, src/apis/image/text/classifications/regnet_y_16gf_v1/regnet_y_16gf_v1.py, src/apis/image/text/classifications/regnet_y_16gf_v2/regnet_y_16gf_v2.py
=> feat(regnet_y_16gf): add regnet_y_16gf to image/text/classification

src/apis/image/text/classifications/vit_l_16_swag_e2e_v1/vit_l_16_swag_e2e_v1.py, src/apis/image/text/classifications/vit_l_16_swag_linear_v1/vit_l_16_swag_linear_v1.py, src/apis/image/text/classifications/vit_l_16_v1/vit_l_16_v1.py
=> feat(vit_l_16): add vit_l_16 to image/text/classification

src/apis/image/text/classifications/regnet_x_8gf_v1/regnet_x_8gf_v1.py, src/apis/image/text/classifications/regnet_x_8gf_v2/regnet_x_8gf_v2.py
=> feat(regnet_x_8gf): add regnet_x_8gf to image/text/classification

src/apis/image/text/classifications/regnet_y_128gf_swag_e2e_v1/regnet_y_128gf_swag_e2e_v1.py, src/apis/image/text/classifications/regnet_y_128gf_swag_linear_v1/regnet_y_128gf_swag_linear_v1.py
=> feat(regnet_y_128gf): add regnet_y_128gf to image/text/classification

src/apis/image/text/classifications/regnet_y_3_2gf_v1/regnet_y_3_2gf_v1.py, src/apis/image/text/classifications/regnet_y_3_2gf_v2/regnet_y_3_2gf_v2.py
=> feat(regnet_y_3_2gf): add regnet_y_3_2gf to image/text/classification

src/apis/image/text/classifications/regnet_y_400mf_v1/regnet_y_400mf_v1.py, src/apis/image/text/classifications/regnet_y_400mf_v2/regnet_y_400mf_v2.py
=> feat(regnet_y_400mf): add regnet_y_400mf to image/text/classification

src/apis/image/text/classifications/regnet_y_8gf_v1/regnet_y_8gf_v1.py, src/apis/image/text/classifications/regnet_y_8gf_v2/regnet_y_8gf_v2.py
=> feat(regnet_y_8gf): add regnet_y_8gf to image/text/classification

src/apis/image/text/classifications/resnext101_32x8d_v1/resnext101_32x8d_v1.py, src/apis/image/text/classifications/resnext101_32x8d_v2/resnext101_32x8d_v2.py
=> feat(resnext101_32x8d): add resnext101_32x8d to image/text/classification

src/apis/image/text/classifications/resnet152_v1/resnet152_v1.py, src/apis/image/text/classifications/resnet152_v2/resnet152_v2.py
=> feat(resnet152): add resnet152 to image/text/classification

src/README.md
This PR documents two entry points to the code for developers, namely : 
* `./run_server_prod.sh` 
* `./main.py`
=> docs(gladia-server): add readme to src

src/api_utils/gladia_api_utils/CoquiEngineHelper.py, src/api_utils/gladia_api_utils/submodules.py
- fix(submodule): fix audio references in submodules.py
- feat(CoquiEngineHelper): add CoquiEngineHelper for STT
=> feat(CoquiEngineHelper): add CoquiEngineHelper for STT

src/.dockerignore, src/gpu.Dockerfile, src/mamba.conf, src/venv-builder/create_custom_envs.py
Closes https://github.com/gladiaio/gladia/issues/436
=> Fix(docker): trying to split into smaller layers

src/api_utils/gladia_api_utils/triton_helper/TritonClient.py, src/apis/text/text/entity-extractions/dbmdz-bert-large-cased-finetuned-conll03-english/dbmdz-bert-large-cased-finetuned-conll03-english.py, src/apis/text/text/hate-speech-detections/Hate-speech-CNERG-dehatebert-mono-english/Hate-speech-CNERG-dehatebert-mono-english.py, src/apis/text/text/sentiment-analyses/nlptown-bert-base-multilingual-uncased-sentiment/nlptown-bert-base-multilingual-uncased-sentiment.py
=> Hide triton_server_url TritonClient's param into kwargs

src/unit-test/test.py
closes: https://github.com/gladiaio/gladia/issues/467
=> ci(test): add capability to filter test (models or wider endpoints)

src/api_utils/gladia_api_utils/casting.py
closes: https://github.com/gladiaio/gladia/issues/479
=> fix(casting): fix int casting

src/licenses-used.md
=> docs(licenses-used.md): update the licences-used.md file

src/apis/image/image/background-removal.py, src/apis/image/image/colorization.py, src/apis/image/image/face-bluring.py, src/apis/image/image/super-resolution.py, src/apis/image/image/uncolorization.py, src/apis/image/text/asciify.py, src/apis/image/text/classification.py, src/apis/image/text/ocr.py, src/unit-test/test.py
closes: https://github.com/gladiaio/gladia/issues/483
=> feat(ttest.png): better default file url

src/api_utils/gladia_api_utils/submodules.py
closes https://github.com/gladiaio/gladia/issues/527
=> fix(api): force input to be interpreted as a json in body

src/api_utils/gladia_api_utils/__init__.py, src/main.py
This PR adds a [Stream Handler](https://docs.python.org/3/library/logging.handlers.html#logging.StreamHandler) to both :
* Gladia `main.py` application
* `gladia_api_utils`
=> feat(logger): add StreamHandler to output on stdout

src/api_utils/gladia_api_utils/__init__.py
=> fix(api_utils): make both loggers go to the same output file via the config file

src/api_utils/gladia_api_utils/submodules.py
Closes #680
Provides a dummy header to urlopen avoiding 403 errors ([cf](https://stackoverflow.com/a/66591873/12625642))
=> fix(TaskRouter): provides dummy header to urlopen

src/apis/image/image/background-removal.py
=> fix(background_removal): change default example

src/apis/text/text/hate-speech-detection-models/byt5-base-tweet-hate-detection/byt5-base-tweet-hate-detection.py, src/apis/text/text/hate-speech-detection.py, src/config.json
Changes:
* add `byt5-base-tweet-hate-detection` model
* switched default model from `hate-speech-detection_bert-base-uncased-hatexplain_base_traced` to `byt5-base-tweet-hate-detection`
* no longer preload `hate-speech-detection_bert-base-uncased-hatexplain_base_traced` as it's no longer the default model
=> feat(hate-speech): byt5-base-tweet-hate-detection

.github/workflows/gladia-builder.yml, .github/workflows/gladia-latest-deploy.yml
action/changed-files : For push events you need to include fetch-depth: 0 OR fetch-depth: 2 depending on your use case.
action/checkout : 
Number of commits to fetch. 0 indicates all history for all branches and tags.
Default: 1
fetch-depth: ''
Setting to 0 now but we need to monitor performance.
=> ci(deploy): fix diff detection

src/apis/image/image/IBasicTestsImageToImage.py, src/apis/image/image/background-removal-models/test_background_removal.py, src/env.yaml, src/pytest.ini, src/tests/constants.py, src/tests/utils/__init__.py, src/tests/utils/get_models_to_test.py
This is a preview of what the functional tests could look like.
Feel free to challenge any choice I made and to ask any question you have.
---
To run the tests be in the `src/` directory and run `python -m pytest apis/`
You can also:
* run `python -m pytest -m mandatory apis/` to run only the mandatory tests
* run `TEST_DEFAULT_MODELS_ONLY=1 python -m pytest apis/` to test only the default models
---
Note : I founded cleaner to set the test file in the same dir as the src file. Otherwise we would have to re-create the all `input/output/task` directories for each task.
=> feat: Base for FT & background removal FTs

src/apis/text/text/headline-generation-models/michau-t5-base-en-generate-headline/michau-t5-base-en-generate-headline.py, src/apis/text/text/headline-generation.py
- feat(headline-generation): add headline generation to apis
- fix(headline-generation): fix max_length
=> feat(headline): add headline generation

src/conftest.py, src/tests/utils/get_models_to_test.py
* `TEST_DEFAULT_MODELS_ONLY` env variable now longer exists
* add `--default-models-only` command line argument to test default models only
=> feat(test): default models only cmd arg

.github/workflows/gladia-latest-deploy.yml
Dumb solution to force the restart. if it fails it might fails forever but we should be able to catch the error.
=> ci(deploy): always restart aipi

src/api_utils/gladia_api_utils/submodules.py
Needed for the following PR improving the FTs
=> fix(submodule): worker no longer crash when local task fail

.github/workflows/gladia-latest-deploy.yml
The goal is to allow external contribution to be promoted
=> ci(deploy): remove secrets

src/apis/text/image/image-generation-models/dream-studio/dream-studio.py
=> fix(dream-studio): no longer returns 2 times the asked number of samples

.github/workflows/gladia-latest-deploy.yml
Check each aipi url to make sure it's up before moving on.
=> ci(deploy): check aipi readiness

.github/workflows/gladia-latest-deploy.yml
Jeez, hopefully this one works or at least give more ideas...
=> ci(deploy): another try to fix slack env webhook

src/apis/image/image/enhancement-models/.task_metadata.yaml
Change test values for enhancement task
=> test(enhancement): change test values

src/apis/image/image/enhancement-models/FiveK/env.yaml, src/apis/image/image/enhancement-models/LOL/env.yaml, src/env.yaml
Closes #813
(temporarily)
cf @jsoto-gladia 
=> perf(enhancement): keep in memory FiveK & LOL models

src/apis/image/image/deblurring-models/CMFNet/CMFNet.py, src/apis/image/image/deblurring-models/CMFNet/model/CMFNet.py, src/apis/image/image/deblurring-models/CMFNet/model/block.py
=> perf(CFMNet): reduce module to imports

src/api_utils/gladia_api_utils/submodules.py
=> fix(TaskRouter): raise HTTPException when clean_kwargs_based_on_router_inputs fails (#839)

src/apis/image/image/guided-inpainting-models/stable-diffusion/stable-diffusion.py
=> fix(guided-inpainting): fix guided-inpainting image resizing

src/apis/image/image/background-removal-models/OnnxBackgroundRemoval.py, src/apis/image/image/background-replacement-models/.task_metadata.yaml
=> fix(background-removal): move from ANTIALIAS to  LANCZOS

src/tools/venv-builder/envs/image/deoldify.yaml
- Set the version of protobuf to 3.20.*
- Env modified for deoldify-artistic and deoldify-stable
=> feat(deoldify): remove 500 error on deoldify model (#848)

src/conftest.py
=> fix(tests): change default port for tests server

src/tests/README.md
Documentation to use a specific model name as a pattern on the pytest module.
=> feat(tests): Support model name as a pattern (#853)

src/apis/image/image/super-resolution-models/latent-sr/ldm/models/diffusion/ddpm.py
=> fix(super-resolution): udpate rank_zero_only import

.github/workflows/upload-api-utils-to-pypi.yaml
=> ci(pypi): fix push to pypi

src/api_utils/gladia_api_utils/__init__.py
=> refactor(api_utils): reduce logs backup to 1

src/api_utils/setup.py
=> fix(api_utils): setup packages

src/api_utils/gladia_api_utils/tester/test_autogenerated.py, src/apis/image/image/background-replacement/test_background_replacement.py, src/apis/image/image/guided-inpainting/test_guided_inpainting.py, src/apis/image/image/inpainting/test_inpainting.py, src/apis/image/text/classification/test_classification.py, src/apis/image/text/ocr/test_ocr.py, src/apis/text/image/image-generation/test_image_generation.py, src/apis/text/text/headline-generation/test_headline_generation.py, src/apis/text/text/keyword-extraction/test_keyword_extraction.py, src/apis/text/text/next-sentence-prediction/test_next_sentence_prediction.py, src/apis/text/text/next-word-prediction/test_next_word_prediction.py, src/apis/text/text/question-answering/test_question_answering.py, src/apis/text/text/similarity/test_similarity.py, src/apis/text/text/summarization/test_summarization.py, src/apis/text/text/translation/test_translation.py, src/apis/text/text/word-alignment/test_word-aligment.py
=> fix: tester is imported from api_utils

src/apis/audio/text/audio-transcription/openai-whisper/.model_metadata.yaml
following openai whisper last night 2 large models were released:
https://github.com/openai/whisper/commit/4179ed2475cc84cba66868b516232ef1b74dacdf
=> feat(whisper): add large-v1 and large-v2

src/apis/image/image/image-guided-inpainting/fantasy-studio/fantasy-studio.py, src/apis/image/image/image-guided-inpainting/image-guided-inpainting.py, src/apis/image/image/image-guided-inpainting/task.yaml
Original Image
+
mask
+
reference
=
=> feat(image-guided-inpainting): add image-guided-inpainting

.github/workflows/gladia-latest-deploy.yml
to reducei this kind of error : https://github.com/gladiaio/gladia/actions/runs/3649540063/jobs/6164564435
it results in the image not being deployed on prod
=> ✨ fix: increase timeout

src/api_utils/gladia_api_utils/submodules.py
=> fix(submodules): fix 968 handle 0 int as valid input

src/apis/text/image/image-generation/stable-diffusion/stable-diffusion.py
=> fix(stable-diffusion): add random seed int 0

src/apis/text/image/image-generation/stable-diffusion/stable-diffusion.py
needs: https://github.com/gladiaio/gladia/pull/969
=> fix(image-generation): set random seed when 0

src/api_utils/gladia_api_utils/submodules.py
=> feat(submodules): retrieve logs from subprocesses

src/prepare.py
faster API server start leveraging cache lookup
=> refactor(prepare): optimize prepare

src/prepare.py
=> perf(prepare): multithread the prepare.py

src/apis/text/text/conversation-summarization/bart-large-xsum-samsum/bart-large-xsum-samsum.py
=> fix(conversation-summarization): use the map reduce algo when it's needed

src/apis/text/text/address-formatting/geopy-formatter/geopy-formatter.py
=> fix(address-formatting): implement a rate limiter

src/apis/text/text/address-formatting/geopy-formatter/geopy-formatter.py
=> fix(address-formatting): return correct message when address not found

src/api_utils/gladia_api_utils/submodules.py, src/apis/image/image/background-replacement/task.yaml
=> feat(submodules): add types Array for the swagger UI

src/apis/audio/text/audio-transcription/openai-whisper/openai-whisper.py
=> fix(audio-transcription/whisper): replace DEFAULT_MODEL to DEFAULT_MODEL["model"]
